export const SET_ORIGIN_COUNTRY = 'SET_ORIGIN_COUNTRY'
export const SET_DESTINATION_COUNTRY = 'SET_DESTINATION_COUNTRY'
export const SET_BID_PRICE = 'SET_BID_PRICE'
export const SET_ASK_PRICE = 'SET_ASK_PRICE'